// import Navbar from "./Navbar";
// import MobileNavbar from "./MobileNavbar";
import styles from "../styles/Home.module.sass";
import Footer from "./Footer";
import Head from "next/head";
import ConditionalNavbar from "./ConditionalNavbar";

const Layout = ({ children }, props) => {
 

  return (
    <>
      <Head>
        <title>💕 G & E&apos;s Wedding 💕</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width,initial-scale=1"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {/* {props.isPhone ? MobileNavbar : Navbar} */}
        <ConditionalNavbar />
        {children}
        <Footer />
      </div>
    </>
  );
};

export default Layout;
