import Head from "next/head";
import styles from "../styles/Home.module.sass";

export default function Home() {
  return (
    <div> 
      <Head>
        <title>💕 G & E's Wedding 💕</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.row}>
          <img className={styles.watercolor} src="/house_watercolor.png" alt="Wedding Venue"></img>
          <div className={styles.info}>
            <h3 className={styles.header}>schedule of events</h3>
            <b>ceremony</b>
            <p>
              saturday, the 13th of august <br/>
              5 o'clock in the evening <br/>
              williams' home <br/>
            </p>
            <b>reception</b>
            <p>
              saturday, the 13th of august <br/>
              6 o'clock in the evening <br/>
              williams' home <br/>
            </p>
            <div>
              <img className={styles.address_box} src="/address_box.png" alt=""></img>
              <p className={styles.address}>
                <i>
                  8855 hunt club road <br/>
                  Zionsville, IN <br/>
                  460777 <br/>
                </i>
              </p>
            </div>
            
          </div>
        </section>
        <section>
          
        </section>

      </main>
    </div>
  );
}
