import Head from "next/head";
import styles from "../styles/Home.module.sass";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>💕 G & E's Wedding 💕</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img className={styles.logo} src="/g+e.png" alt="logo"></img>
        <nav className={styles.nav}>
          <ul className={styles.nav_links}>
            <li>
              <a href="#">details</a>
            </li>
            <li>
              <a href="#">our story</a>
            </li>
            <li>
              <a href="#">registry</a>
            </li>
            <li>
              <a href="#">where to stay</a>
            </li>
            <li>
              <a href="#">gallery</a>
            </li>
          </ul>
        </nav>

        <section>
          <h2></h2>
        </section>

      </main>
    </div>
  );
}
